name: Hola Mundo

on: [push]

jobs:
  hola:
    runs-on: ubuntu-latest
    steps:
      - name: hola mundo
        run: echo "holamundo"
      - name: touch file
        run: touch helloworld.txt
      - name: set text
        run: echo "hello world!" >> helloworld.txt
      - name: read file
        run: cat helloworld.txt
  other:
    runs-on: ubuntu-latest
    steps:
      - name: LS
        run: ls -la