name: Hola Mundo

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  hola:
    runs-on: ubuntu-latest
    steps:
      - name: hola mundo
        run: echo "holamundo"
      - name: touch file
        run: touch helloworld.txt
      - name: set text
        run: echo "hello world!" >> helloworld.txt
      - name: read file
        run: cat helloworld.txt
  other:
    runs-on: ubuntu-latest
    needs: hola
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: LS
        run: ls -la
      
      - name: Checkout
        uses: actions/checkout@v4.1.7
    
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        with:
          node-verion: latest
      
      - name: node version
        run: node --version
      
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.31.1
        with:
          php-version: '8.3'

      - name: php version
        run: php --version
  say-hello:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: example
        ports:
          - 3306:3306
      redis:
        image: redis
        ports:
          - 6379:6379
    env:
      MY_VAR: my secret 
    steps:
      - name: Test
        env:
          MY_STEP_VAR: my step secret
        run: echo "valor ${MY_STEP_VAR}"