name: Hola Mundo

on: [push]

jobs:
  hola:
    runs-on: ubuntu-latest
    steps:
      - name: hola mundo
        run: echo "holamundo"
      - name: touch file
        run: touch helloworld.txt
      - name: set text
        run: echo "hello world!" >> helloworld.txt
      - name: read file
        run: cat helloworld.txt
  other:
    runs-on: ubuntu-latest
    needs: hola
    steps:
      - name: LS
        run: ls -la
      
      - name: Checkout
        uses: actions/checkout@v4.1.7
    
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
      
      - name: node version
        run: node --version
    